### ISSUE TITLE
Question about testing on multi-scale

### ISSUE THREAD

**Issue by wsh2836741** [MhLiao/TextBoxes#87]
Thanks for excellent work.But i am confused,it said 'out of memory' when i use titan xp GPU(12G).And the largest scale i can use is 1100*1100.Thank you in advice.

**Comment by MhLiao** [comment]
Do you use cudnn? It should not suffer "out of memory" when the largest scale is 1600*1600 with a titan xp.

**Comment by wsh2836741** [comment]
thx，i have solved the problem by using cudnn，and 8G is enough.

**Comment by larklili** [comment]
hello,when I run demo.py.It has the following errors:
F0510 10:28:22.312146 15884 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
what should i do?I have changed the scales,like this:
scales=((300,300),(700,700),(700,500),(700,300),(1100,1100))

**Comment by sungwonida** [comment]
> Do you use cudnn? It should not suffer "out of memory" when the largest scale is 1600*1600 with a titan xp.  

Thank you. `USE_CUDNN := 1` solved the issue.
